version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-uploader"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o9p6qnwsutlu"
s3_prefix = "s3-uploader"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "UserPoolId=\"eu-central-1_L8jkGP4ve\" Audience=\"5rkm868lb75gf9jek6lpccl1r5\""
